<a href="https://colab.research.google.com/github/23070744-hue/pract1NNDL/blob/main/prac1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

vector_sum = vector1 + vector2

print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Vector Addition:", vector_sum)

matrix1 = np.array([[1, 2],
                    [3, 4]])

matrix2 = np.array([[5, 6],
                    [7, 8]])

matrix_product = np.matmul(matrix1, matrix2)

print("\nMatrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nMatrix Multiplication:")
print(matrix_product)

Vector 1: [1 2 3]
Vector 2: [4 5 6]
Vector Addition: [5 7 9]

Matrix 1:
[[1 2]
 [3 4]]

Matrix 2:
[[5 6]
 [7 8]]

Matrix Multiplication:
[[19 22]
 [43 50]]
